### PR TITLE
Add StackExchange API Scrapper

### LINKED ISSUE #87: Update Bitcoin Stack Exchange Scraping Process
Our scraper is designed to keep track of content from multiple Bitcoin-related sources, including the Bitcoin Stack Exchange. Currently, however, we haven’t received new data from the Bitcoin Stack Exchange in over seven months. This is because the [source we were using](https://archive.org/download/stackexchange/bitcoin.stackexchange.com.7z) for periodic data dumps is no longer being updated.

### Problem:
- The previous data dump process on Archive.org has been changed, as detailed in Stack Exchange's [announcement](https://meta.stackexchange.com/questions/401324/announcing-a-change-to-the-data-dump-process).
- Stack Exchange now requires organizations to [become a partner](https://stackoverflow.co/api-solutions/) to access the data dump, but our partnership application was denied.

### Proposed Solution:
- Since direct data dumps are unavailable, the alternative is to fetch content using the Stack Exchange API. This will allow us to continue updating the Bitcoin Stack Exchange content in our Elasticsearch index, ensuring we have the latest data.

### Tasks:
1. **Investigate Stack Exchange API documentation** and identify the endpoints required to fetch relevant data.
2. **Modify the scraping workflow** to replace the data dump process with API-based data collection.
3. **Set up API rate-limiting and scheduling** to align with Stack Exchange's usage policies, ensuring that our nightly cron jobs run smoothly.

### PR DESCRIPTION
**Pull request by elraphty**
This PR adds the functionality to get bitcoin stack exchange questions and answers using APIs and add to our ES index

Closes #87

### CODE REVIEW

**Comment by kouloumos** [comment]
@elraphty can you add my own branch as the target branch for this so it's easier to review the changes?

Also, how can I test this? Can you provide the flow?

**Comment by elraphty** [comment]
> @elraphty can you add my own branch as the target branch for this so it's easier to review the changes?
> 
> Also, how can I test this? Can you provide the flow?

your branch is not on this repo yet, which means I will have to make the PR to your forked repo

**Comment by kouloumos** [comment]
> your branch is not on this repo yet, which means I will have to make the PR to your forked repo

I just merged my PR with master, so you can proceed.

**Comment by elraphty** [comment]
> @elraphty can you add my own branch as the target branch for this so it's easier to review the changes?
> 
> Also, how can I test this? Can you provide the flow?

@kouloumos How to run 
``` 
      stack_exchange = StackExchangeScraper()

      stack_exchange.get_json()
      stack_exchange.format_data()
```

**Review by kouloumos — CHANGES_REQUESTED** [review]
@elraphty, it seems that you didn't correctly rebased this. d25ce2a2a970c2fc27d322bf601af4df01cba473 and 82b31e98421dec84ae3fdaf0761fd3d10770aa8e are actually removing the latest changes that I introduced.

Let me know if you need help with rebasing. Simple solution would be to create a new branch from master and then cherry-pick the rest of your commits on that. You are not modifying existing files, so that should work without any issues.

**Comment by elraphty** [comment]
> @elraphty, it seems that you didn't correctly rebased this. [d25ce2a](https://github.com/bitcoinsearch/scraper/commit/d25ce2a2a970c2fc27d322bf601af4df01cba473) and [82b31e9](https://github.com/bitcoinsearch/scraper/commit/82b31e98421dec84ae3fdaf0761fd3d10770aa8e) are actually removing the latest changes that I introduced.
> 
> Let me know if you need help with rebasing. Simple solution would be to create a new branch from master and then cherry-pick the rest of your commits on that. You are not modifying existing files, so that should work without any issues.

oh! okay, the merge conflicts were a lot, guessed I made a mistake will resolving the some merge conflicts while rebasing, I will close and create a new PR

**Pull request closed without merging**
