### PR TITLE
Feat: added stackexchange api scrapper

### LINKED ISSUE #87: Update Bitcoin Stack Exchange Scraping Process
Our scraper is designed to keep track of content from multiple Bitcoin-related sources, including the Bitcoin Stack Exchange. Currently, however, we haven’t received new data from the Bitcoin Stack Exchange in over seven months. This is because the [source we were using](https://archive.org/download/stackexchange/bitcoin.stackexchange.com.7z) for periodic data dumps is no longer being updated.

### Problem:
- The previous data dump process on Archive.org has been changed, as detailed in Stack Exchange's [announcement](https://meta.stackexchange.com/questions/401324/announcing-a-change-to-the-data-dump-process).
- Stack Exchange now requires organizations to [become a partner](https://stackoverflow.co/api-solutions/) to access the data dump, but our partnership application was denied.

### Proposed Solution:
- Since direct data dumps are unavailable, the alternative is to fetch content using the Stack Exchange API. This will allow us to continue updating the Bitcoin Stack Exchange content in our Elasticsearch index, ensuring we have the latest data.

### Tasks:
1. **Investigate Stack Exchange API documentation** and identify the endpoints required to fetch relevant data.
2. **Modify the scraping workflow** to replace the data dump process with API-based data collection.
3. **Set up API rate-limiting and scheduling** to align with Stack Exchange's usage policies, ensuring that our nightly cron jobs run smoothly.

### PR DESCRIPTION
**Pull request by elraphty**
This PR adds the functionality to get bitcoin stack exchange questions and answers using APIs and add to our ES index

Closes #87 

How to run 
``` 
      stack_exchange = StackExchangeScraper()

      stack_exchange.get_json()
      stack_exchange.format_data()
```

### CODE REVIEW

**Review by kouloumos — COMMENTED** [review]
@elraphty I reviewed the code and push some changes with 6048bad02bb9e2ae841b963692fe88a2270d7aa1 to fit your implementation into the current scraper architecture.
Alongside the changes I fixed the following issues:
- duplicate `tags`
- wrong `thread_url`
- wrong format for `created_at`
- addition of `body_formatted` with html format
- `accepted_answer_id` only for questions

You can test the changes and validate that everything is working using the command line interface:
```
scraper scraper --source stackecxhange
```

Use  `--output=mock` to store the output in a json file. You can find more information about available commands in the README.

Please review the new code and verify that this is working.

**Comment by elraphty** [comment]
> @elraphty I reviewed the code and push some changes with [6048bad](https://github.com/bitcoinsearch/scraper/commit/6048bad02bb9e2ae841b963692fe88a2270d7aa1) to fit your implementation into the current scraper architecture. Alongside the changes I fixed the following issues:
> 
> * duplicate `tags`
> * wrong `thread_url`
> * wrong format for `created_at`
> * addition of `body_formatted` with html format
> * `accepted_answer_id` only for questions
> 
> You can test the changes and validate that everything is working using the command line interface:
> 
> ```
> scraper scraper --source stackecxhange
> ```
> 
> Use `--output=mock` to store the output in a json file. You can find more information about available commands in the README.
> 
> Please review the new code and verify that this is working.

I think this looks good, I will try running it locally today

**Comment by elraphty** [comment]
> --output=mock

@kouloumos When I try to use the scrapper command `scraper --source stackecxhange --output=mock` I got scrapper not found, and when i installed poetry to try to use poetry ` poetry run scraper --source stackecxhange --output=mock` I get this error `Poetry could not find a pyproject.toml file in /Users/raphaelosazeeyerin/Desktop/Chaincode or its parents`

**Comment by kouloumos** [comment]
> When I try to use the scrapper command ...

Did you follow the [installation instructions](https://github.com/bitcoinsearch/scraper/tree/master/scraper#installation)? You need to also run `poetry install`. And from the error, it seems that you are not in the scraper directory?

**Comment by elraphty** [comment]
> > When I try to use the scrapper command ...
> 
> Did you follow the [installation instructions](https://github.com/bitcoinsearch/scraper/tree/master/scraper#installation)? You need to also run `poetry install`. And from the error, it seems that you are not in the scraper directory?

Yeah, just discovered it is caused by my python version, will upgrade my python and try again

**Comment by elraphty** [comment]
> > > When I try to use the scrapper command ...
> > 
> > 
> > Did you follow the [installation instructions](https://github.com/bitcoinsearch/scraper/tree/master/scraper#installation)? You need to also run `poetry install`. And from the error, it seems that you are not in the scraper directory?
> 
> Yeah, just discovered it is caused by my python version, will upgrade my python and try again

@kouloumos which python version are you using? i have switched to python3.11,  some of the packages return this error `ERROR: Could not find a version that satisfies the requirement git (from versions: none)
ERROR: No matching distribution found for git`

**Comment by elraphty** [comment]
> > > > When I try to use the scrapper command ...
> > > 
> > > 
> > > Did you follow the [installation instructions](https://github.com/bitcoinsearch/scraper/tree/master/scraper#installation)? You need to also run `poetry install`. And from the error, it seems that you are not in the scraper directory?
> > 
> > 
> > Yeah, just discovered it is caused by my python version, will upgrade my python and try again
> 
> @kouloumos which python version are you using? i have switched to python3.11, some of the packages return this error `ERROR: Could not find a version that satisfies the requirement git (from versions: none) ERROR: No matching distribution found for git`

@kouloumos It works for me now on python3.12, there was a typo with scraper scraper --source `stackecxhange`, changed to `stackexchange`, you can merge.

**Comment by kouloumos** [comment]
This is good to merge, but there are a few limitations to have in mind:

- Timeframe: The current setup checks only the latest posts from the past 7 days. This timeframe may need to be adjusted based on future requirements.
- API Quotas: Due to limited quotas, we can’t scrape everything. However, since there’s not much activity on the website, running the process once a day should keep us within quota limits.
- Edited Posts: The current setup doesn’t account for edited posts. Since it’s common for posts to be updated, this could become an issue.

**Pull request merged**
