### PR TITLE
Changes to use Elastic client instead of App search

### PR DESCRIPTION
**Pull request by ivssh**
- [x] Create Elasticsearch client connection
- [x] Use bulk helpers to bulk index

### CODE REVIEW

**Comment by ivssh** [comment]
@adamjonas Please review the same

**Comment by ivssh** [comment]
Added Javascript client as well to the scraper. Also tested the same.

**Comment by adamjonas** [comment]
Great! I'd strongly prefer you create a duplicate file rather than replace the app search scrapers so that we have the luxury of switching over gradually as we add all the necessary scrapers. With this example as a template, we can start working on those other files.

**Comment by adamjonas** [comment]
Superseded by #20

**Pull request closed without merging**
